### ISSUE TITLE
Code Analysis

### ISSUE THREAD

**Issue by fzsoca** [fenyopeti/CSharpVerbalExpressions#2]
Using Visual Studio Code Analyzer, we conduct static source code analysis.

**Comment by fzsoca** [comment]
We've concluded the static source code analysis, our findings can be found on the project's Wiki-page.

**Comment by micskeiz** [comment]
How about trying an other tool to see whether it can find any smells in the code? SonarQube can also check C#. Or did you try to change the ruleset of VS Analyzer?

**Comment by metzing** [comment]
Managed to set up SonarQube as you proposed.
